#!/bin/sh

# This script is to create a new user with the given user and group ID and run the specified command as him.

UID=${UID:-1000}
GID=${GID:-1000}

addgroup -S user -g $GID && \
        adduser -S -D -H -h $(pwd) -s /bin/sh -u $UID -G user -g user user

chown -R $GID:$UID $(pwd) $CHOWN

su -s /bin/sh -c "$@" user
