syncthing:
  image: zburgermeiszter/syncthing:0.14.3
  ports:
   - 8384:8384
   - 22000:22000
   - 21027:21027/udp
  volumes:
    - ./data:/syncthing
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .env
  restart: unless-stopped

syncthing-inotify:
  image: zburgermeiszter/syncthing-inotify:0.8.3
  links:
    - syncthing:syncthing
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - syncthing
  env_file:
    - .env
  restart: unless-stopped